### ISSUE TITLE
提交到F-Droid商店

### ISSUE THREAD

**Issue by StarsbySea** [cooaer/V2Compose#1]
感觉是挺合适的，不过就是要写一个符合要求的构建脚本就是了。

**Comment by cooaer** [comment]
可以的！有空我研究一下怎么提交到F-Droid!

**Comment by alaskasquirrel** [comment]
[IzzyOnDroid F-Droid Repository](https://apt.izzysoft.de/fdroid/) 也是个不错的提交选择

**Comment by cooaer** [comment]
已提交至 F-droid，https://f-droid.org/packages/io.github.v2compose/
