### ISSUE TITLE
回复帖子时回车后输入中文异常

### ISSUE THREAD

**Issue by velviagris** [cooaer/V2Compose#10]
我在回复一篇帖子时第一行输入了邮箱，想在第二行输入补充内容，但输入不了。

**Comment by cooaer** [comment]
你能复现这个问题吗？
请反馈一下你当时输入的是什么内容？

**Comment by velviagris** [comment]
> 你能复现这个问题吗？
> 请反馈一下你当时输入的是什么内容？

试了一下复现不了，我先关了这个issue吧
