### ISSUE TITLE
主页选择「全部」时可以考虑分页加载更多的帖子

### ISSUE THREAD

**Issue by nghoiban** [cooaer/V2Compose#2]
现在主页选择「全部」时没有加载 “全部” 的帖子，只加载了很少一部分。
希望可以实现加载 “全部” 的帖子，至少是最近两三天内的帖子都可以看到，那样话感觉比较合理。

**Comment by cooaer** [comment]
V2compose的数据是从v2ex.com上抓取的，V2compose的主页“全部”对应的是v2ex.com主页的“全部”，v2ex.com的“全部”是无法加载更多的。
按照你的需求，我可能会考虑增加一个“最近”的tab，数据来源是[v2ex.com/recent](https://v2ex.com/recent)。
你看能满足你的需求吗？

**Comment by nghoiban** [comment]
可以满足，谢谢。你客气了，我只是建议

我刚看了下 v2ex 的「全部」，主页「全部」页面右下角有个「更多」，这个「更多」就是取的  https://v2ex.com/recent
你单独做一个「最近」的 tab 也是可以的

另外之前一直用的「V2er」这个客户端，但现在发现「V2compose」有些地方做得更好，但也有很多地方可以完善💪

**Comment by cooaer** [comment]
嗯嗯，欢迎提建议！

**Comment by nghoiban** [comment]
使用了一段时间，发现如果要看更多的内容还要左划两次切换到「最近」那个标签下，感觉还是很不方便。能不能在「全部」标签里加上「最近」标签的内容，就是「全部」标签内容展示完了，如果继续刷则调用「最近」标签的接口，这样只刷「全部」标签就可以看到所有内容，也就是现在 V2er 的实现，可以考虑下。事实上大多数人刷 V2ex 应该只会刷一个标签，这也是V2er 默认好像就是展示一个「全部」标签。

**Comment by cooaer** [comment]
主页的tab对应的是官网首页的各个tab，把全部和最近混在一起并不是一个很好的解决方案，可能会给其他用户造成困扰。
我之前有考虑过允许用户自定义主页顶部tab的顺序，如果第一个是最近，就能解决你的问题，但是compose的drag and drop列表组件不成熟，只能放弃。
我会考虑调整主页tab的顺序，把最近作为第一个tab！

**Comment by nghoiban** [comment]
谢谢你的考虑，不过我觉得还是不要把「最近」标签放在第一位。

因为「最近」标签的帖子数据不是最新的，放在第一位使用的人会看不到最新的内容，会不理解，没必要我一个人的需求影响了所有用户。

我的需求其实是在一个标签内看到所有的数据（所有的数据=「全部」+「最近」）而不用切换标签，所以其实你即使把「最近」标签放在第一位也满足不了我的需求。

所以优先考虑实现用户可以自己调整标签顺序吧，这个看来是目前的最优解。如果实现困难的话，可以暂时放下，哪天有更好的解决方案再说。
