### ISSUE TITLE
Google无法登录

### ISSUE THREAD

**Issue by bilibili2233a** [cooaer/V2Compose#7]
一点登录了就会在登录界面停留十几秒。
https://user-images.githubusercontent.com/99982054/233511243-39ea5a3e-f5b7-408a-bebe-fcf3ca68bf0c.mp4

过了十几秒就一直在网页里停留着
https://user-images.githubusercontent.com/99982054/233511331-fdb0831a-ec01-4a1f-b020-016c5a2ede00.mp4

**设备型号**：华为mate20PRO
**系统**: HarmonyOS3.0.150log版, Android 10
**代理软件**: clash for Android
**代理协议**：Trojan、vmess、Shadowsocks都试过
**系统WebView**:Android System WebView（Google版）
**WebView版本**:110.0.5481.65 (548106534)

**Comment by cooaer** [comment]
OK，收到问题，稍后会解决一下！

**Comment by cooaer** [comment]
已修复，下载安装1.0.1版本即可登录！
